import { db } from '@/lib/db/schema';
import { Decision, Review } from '@/lib/types';

/**
 * Sample data for testing and demonstration
 */
const sampleDecisions: Decision[] = [
  {
    title: 'Switch to React from Vue',
    reasoning: 'Our team was struggling with Vue component architecture. React has better ecosystem support and more team members know it.',
    confidence: 75,
    decision_type: 'work',
    importance: 'high',
    decision_speed: 'moderate',
    decision_driver: 'logic',
    expected_outcome: 'Faster development cycles, easier onboarding for new developers',
    review_date: new Date('2025-11-15'),
    created_at: new Date('2025-08-10'),
  },
  {
    title: 'Declined promotion to stay on technical track',
    reasoning: 'Felt that staying hands-on with code was more fulfilling than management. The promotion would take me away from coding.',
    confidence: 85,
    decision_type: 'work',
    importance: 'high',
    decision_speed: 'slow',
    decision_driver: 'logic',
    expected_outcome: 'Continue growing technical skills while avoiding management overhead',
    review_date: new Date('2025-12-20'),
    created_at: new Date('2025-09-01'),
  },
  {
    title: 'Invested in cryptocurrency',
    reasoning: 'Market was bullish, friends were making money. Decided to allocate 5% of portfolio to diversify.',
    confidence: 45,
    decision_type: 'finance',
    importance: 'medium',
    decision_speed: 'quick',
    decision_driver: 'opportunity',
    expected_outcome: 'Potential 10x returns if market continues upward',
    review_date: new Date('2026-01-30'),
    created_at: new Date('2025-10-15'),
  },
  {
    title: 'Started morning running routine',
    reasoning: 'New Year resolution. Wanted to improve fitness and establish a healthy habit. Started with 3 days a week.',
    confidence: 65,
    decision_type: 'health',
    importance: 'medium',
    decision_speed: 'moderate',
    decision_driver: 'external_pressure',
    expected_outcome: 'Build consistent exercise habit, improve cardiovascular health within 3 months',
    review_date: new Date('2026-02-01'),
    created_at: new Date('2025-12-31'),
  },
  {
    title: 'Hired junior developer without coding assessment',
    reasoning: 'Great interview, strong culture fit, resume was solid. Time-pressed to fill the role. Made quick judgment call.',
    confidence: 50,
    decision_type: 'work',
    importance: 'high',
    decision_speed: 'quick',
    decision_driver: 'urgency',
    expected_outcome: 'Reduce hiring time, bring in fresh perspective even with mentoring required',
    review_date: new Date('2026-02-10'),
    created_at: new Date('2025-11-20'),
  },
  {
    title: 'Bought premium coffee equipment',
    reasoning: 'Was spending $8 per coffee daily. Expensive equipment would pay for itself in 2 months. Want more control over quality.',
    confidence: 80,
    decision_type: 'personal',
    importance: 'low',
    decision_speed: 'slow',
    decision_driver: 'logic',
    expected_outcome: 'Save money long-term while enjoying better quality coffee at home',
    review_date: new Date('2026-02-15'),
    created_at: new Date('2025-12-15'),
  },
  {
    title: 'Quit gym membership and started home workouts',
    reasoning: 'Gym was inconvenient, commute took 30 mins. Started YouTube workouts at home which fits my schedule better.',
    confidence: 70,
    decision_type: 'health',
    importance: 'medium',
    decision_speed: 'moderate',
    decision_driver: 'logic',
    expected_outcome: 'Save monthly cost and increase consistency due to convenience',
    review_date: new Date('2026-02-08'),
    created_at: new Date('2025-11-01'),
  },
  {
    title: 'Delayed refactoring project to prioritize new features',
    reasoning: 'Product roadmap was demanding new features. Technical debt could wait. Management pushed for deliverables.',
    confidence: 40,
    decision_type: 'work',
    importance: 'high',
    decision_speed: 'quick',
    decision_driver: 'external_pressure',
    expected_outcome: 'Meet quarterly OKRs, plan refactoring for Q2',
    review_date: new Date('2026-02-12'),
    created_at: new Date('2025-12-01'),
  },
  {
    title: 'Reconnected with old friend after 5 years',
    reasoning: 'Saw them on social media and reached out on a whim. Was nervous about awkwardness but decided to be brave.',
    confidence: 60,
    decision_type: 'personal',
    importance: 'low',
    decision_speed: 'quick',
    decision_driver: 'opportunity',
    expected_outcome: 'Rebuild old friendship, reminisce about good times',
    review_date: new Date('2026-01-25'),
    created_at: new Date('2025-10-20'),
  },
  {
    title: 'Chose affordable apartment over dream location',
    reasoning: 'Dream apartment was 40% more expensive. Chose something 20 mins further but with better financial cushion.',
    confidence: 78,
    decision_type: 'personal',
    importance: 'high',
    decision_speed: 'slow',
    decision_driver: 'logic',
    expected_outcome: 'Better financial security while sacrificing location convenience',
    review_date: new Date('2026-02-05'),
    created_at: new Date('2025-09-15'),
  },
  {
    title: 'Switched to new project management tool',
    reasoning: 'Old tool was clunky. New one had better integrations. Team was hesitant but I pushed for it.',
    confidence: 62,
    decision_type: 'work',
    importance: 'medium',
    decision_speed: 'moderate',
    decision_driver: 'logic',
    expected_outcome: 'Improved workflow efficiency and team velocity',
    review_date: new Date('2026-02-20'),
    created_at: new Date('2025-11-10'),
  },
  {
    title: 'Skipped vacation to meet project deadline',
    reasoning: 'Project was critical for company. Vacation could be rescheduled. Felt responsible to stay.',
    confidence: 45,
    decision_type: 'work',
    importance: 'high',
    decision_speed: 'quick',
    decision_driver: 'external_pressure',
    expected_outcome: 'Deliver on time, prevent team burnout',
    review_date: new Date('2026-02-18'),
    created_at: new Date('2025-12-20'),
  },
  {
    title: 'Accepted side project for extra income',
    reasoning: 'Extra $500/month could help build emergency fund. Would require 5 hours/week commitment.',
    confidence: 55,
    decision_type: 'finance',
    importance: 'medium',
    decision_speed: 'moderate',
    decision_driver: 'opportunity',
    expected_outcome: 'Build savings faster without impacting main job',
    review_date: new Date('2026-02-10'),
    created_at: new Date('2025-12-05'),
  },
  {
    title: 'Cut out sugar completely',
    reasoning: 'Read about health benefits. Wanted to reset eating habits. Decided cold turkey approach.',
    confidence: 40,
    decision_type: 'health',
    importance: 'medium',
    decision_speed: 'quick',
    decision_driver: 'fear',
    expected_outcome: 'Feel more energetic, lose weight, improve health markers',
    review_date: new Date('2026-02-14'),
    created_at: new Date('2025-12-28'),
  },
  {
    title: 'Paid for online course upfront instead of free alternative',
    reasoning: 'Free course had mixed reviews. Paid option had structure and community. Investment = commitment.',
    confidence: 72,
    decision_type: 'personal',
    importance: 'low',
    decision_speed: 'moderate',
    decision_driver: 'logic',
    expected_outcome: 'Complete course and gain new skills faster than free option',
    review_date: new Date('2026-02-16'),
    created_at: new Date('2025-12-10'),
  },
  {
    title: 'Confronted coworker about missed deadline',
    reasoning: 'They missed deadline affecting my work. Was nervous but decided direct conversation was better than escalating.',
    confidence: 68,
    decision_type: 'work',
    importance: 'medium',
    decision_speed: 'slow',
    decision_driver: 'logic',
    expected_outcome: 'Clear communication, prevent future issues, maintain relationship',
    review_date: new Date('2026-02-12'),
    created_at: new Date('2026-01-15'),
  },
  {
    title: 'Bought used car instead of financing new one',
    reasoning: 'New car would cost $30k with financing. Used car $8k upfront. Willing to take maintenance risk.',
    confidence: 75,
    decision_type: 'finance',
    importance: 'high',
    decision_speed: 'slow',
    decision_driver: 'logic',
    expected_outcome: 'Save significantly on payments while accepting higher maintenance risk',
    review_date: new Date('2026-01-28'),
    created_at: new Date('2025-10-01'),
  },
  {
    title: 'Started meditation practice',
    reasoning: 'Stress was high. Meditation seemed helpful. Committed to 10 minutes daily.',
    confidence: 58,
    decision_type: 'health',
    importance: 'medium',
    decision_speed: 'moderate',
    decision_driver: 'logic',
    expected_outcome: 'Reduce stress and anxiety, improve focus',
    review_date: new Date('2026-02-08'),
    created_at: new Date('2026-01-08'),
  },
  {
    title: 'Changed diet to Mediterranean style',
    reasoning: 'Research shows benefits for heart health and longevity. More sustainable than keto.',
    confidence: 70,
    decision_type: 'health',
    importance: 'high',
    decision_speed: 'slow',
    decision_driver: 'logic',
    expected_outcome: 'Better long-term health and sustainable eating habits',
    review_date: new Date('2026-02-17'),
    created_at: new Date('2025-11-20'),
  },
  {
    title: 'Negotiated salary increase',
    reasoning: 'Been in role 3 years, no raise. Market rate was higher. Prepared data, had conversation with manager.',
    confidence: 65,
    decision_type: 'work',
    importance: 'high',
    decision_speed: 'slow',
    decision_driver: 'logic',
    expected_outcome: 'Get 10-15% raise to match market rate',
    review_date: new Date('2026-02-11'),
    created_at: new Date('2025-11-15'),
  },
  {
    title: 'Invested in stock index fund instead of individual stocks',
    reasoning: 'Read about fees and performance. Index fund seemed lower risk and less time-intensive.',
    confidence: 80,
    decision_type: 'finance',
    importance: 'high',
    decision_speed: 'slow',
    decision_driver: 'logic',
    expected_outcome: 'Long-term wealth building with lower stress',
    review_date: new Date('2026-02-19'),
    created_at: new Date('2025-10-10'),
  },
  {
    title: 'Joined networking group for career growth',
    reasoning: 'Wanted to expand professional network. Found local group meeting monthly. Committed to attending.',
    confidence: 62,
    decision_type: 'work',
    importance: 'medium',
    decision_speed: 'moderate',
    decision_driver: 'opportunity',
    expected_outcome: 'Build relationships, discover opportunities, learn from peers',
    review_date: new Date('2026-02-09'),
    created_at: new Date('2025-12-15'),
  },
  {
    title: 'Said no to friends\' weekend trip',
    reasoning: 'Important family event same weekend. Felt guilty but knew family was priority for me.',
    confidence: 85,
    decision_type: 'personal',
    importance: 'medium',
    decision_speed: 'quick',
    decision_driver: 'logic',
    expected_outcome: 'Maintain family relationships, feel aligned with values',
    review_date: new Date('2026-02-06'),
    created_at: new Date('2025-12-30'),
  },
  {
    title: 'Switched dentist for better reviews',
    reasoning: 'Previous dentist had mediocre reviews and was expensive. New one had excellent ratings at lower cost.',
    confidence: 73,
    decision_type: 'health',
    importance: 'low',
    decision_speed: 'moderate',
    decision_driver: 'logic',
    expected_outcome: 'Better dental care and save money on procedures',
    review_date: new Date('2026-02-13'),
    created_at: new Date('2025-11-25'),
  },
  {
    title: 'Decided to learn programming language',
    reasoning: 'Career path could benefit from it. Spent 3 months researching language choice before committing.',
    confidence: 77,
    decision_type: 'work',
    importance: 'high',
    decision_speed: 'slow',
    decision_driver: 'opportunity',
    expected_outcome: 'Expand skill set and improve career prospects',
    review_date: new Date('2026-02-15'),
    created_at: new Date('2025-10-20'),
  },
  {
    title: 'Reduced social media usage',
    reasoning: 'Was spending 2+ hours daily. Decided to limit to 20 mins before bed only.',
    confidence: 58,
    decision_type: 'personal',
    importance: 'low',
    decision_speed: 'quick',
    decision_driver: 'fear',
    expected_outcome: 'More free time, better mental health, improved focus',
    review_date: new Date('2026-02-07'),
    created_at: new Date('2026-01-20'),
  },
  {
    title: 'Bought expensive ergonomic desk chair',
    reasoning: 'Back pain from sitting 8 hours daily. Good chair could prevent health issues. $600 investment.',
    confidence: 76,
    decision_type: 'personal',
    importance: 'medium',
    decision_speed: 'slow',
    decision_driver: 'logic',
    expected_outcome: 'Reduce back pain, improve posture, prevent chronic issues',
    review_date: new Date('2026-02-14'),
    created_at: new Date('2025-12-01'),
  },
  {
    title: 'Applied to dream job even though underqualified',
    reasoning: 'Had 70% of required skills. Thought worst they could say is no. Applied anyway.',
    confidence: 40,
    decision_type: 'work',
    importance: 'high',
    decision_speed: 'moderate',
    decision_driver: 'opportunity',
    expected_outcome: 'Possible interview opportunity or at least valuable experience',
    review_date: new Date('2026-02-21'),
    created_at: new Date('2026-01-05'),
  },
  {
    title: 'Ended toxic friendship',
    reasoning: 'Friend was consistently negative and draining. Tried talking, no change. Decided to distance.',
    confidence: 72,
    decision_type: 'personal',
    importance: 'high',
    decision_speed: 'slow',
    decision_driver: 'logic',
    expected_outcome: 'Reduce stress, focus energy on positive relationships',
    review_date: new Date('2026-02-11'),
    created_at: new Date('2025-09-20'),
  },
];

const sampleReviews: Omit<Review, 'created_at' | 'decision_id'>[] = [
  {
    expectation_comparison: 'slightly_better',
    decision_quality: 'reasonable',
    surprise_score: 25,
    what_happened: 'React adoption went smoother than expected. Component reusability improved development speed by ~15%.',
    learning_note: 'Ecosystem does matter. Had good documentation and community support. Should have migrated earlier.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'as_expected',
    decision_quality: 'very_thoughtful',
    surprise_score: 10,
    what_happened: 'Stayed technical, contributed to several key projects, mentored 2 junior developers. Feeling satisfied.',
    learning_note: 'Made the right call for my personality. Realized I value autonomy and hands-on work more than leadership title.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'much_worse',
    decision_quality: 'emotional',
    surprise_score: 95,
    what_happened: 'Invested $5,000, dropped to $1,200 within months. Market crash hit harder than expected.',
    learning_note: 'FOMO is a terrible investment strategy. Should have done more research before jumping in. Confidence was too low to begin with.',
    would_repeat: 'no',
  },
  {
    expectation_comparison: 'as_expected',
    decision_quality: 'reasonable',
    surprise_score: 20,
    what_happened: 'Running 3x weekly for 2 months now. Built decent habit, feeling healthier and more energetic.',
    learning_note: 'Morning runs are working well for me. Need to be consistent through spring when weather gets better.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'slightly_worse',
    decision_quality: 'rushed',
    surprise_score: 60,
    what_happened: 'Junior dev is struggling with foundational concepts. Requires 2-3x more mentoring than typical hire.',
    learning_note: 'Coding assessment would have revealed gaps. Saved 2 weeks in hiring but cost 40 hours in mentoring already. False economy.',
    would_repeat: 'no',
  },
  {
    expectation_comparison: 'much_better',
    decision_quality: 'very_thoughtful',
    surprise_score: 15,
    what_happened: 'Equipment paid for itself in 6 weeks. Making better coffee than before. Morning ritual improved.',
    learning_note: 'Good financial decision that also improved quality of life. Solving the convenience problem was the real win.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'slightly_better',
    decision_quality: 'reasonable',
    surprise_score: 30,
    what_happened: 'Home workouts became consistent. Saved $40/month. Energy levels improved more than expected.',
    learning_note: 'Convenience is underrated. The 30 min commute was the real barrier. Small wins compound.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'slightly_worse',
    decision_quality: 'rushed',
    surprise_score: 70,
    what_happened: 'Technical debt compounded. New features became harder to build. Refactoring now taking 3x longer than if we had planned.',
    learning_note: 'Kicking the can down the road always costs more. Should have negotiated for at least 20% refactoring time.',
    would_repeat: 'no',
  },
  {
    expectation_comparison: 'much_better',
    decision_quality: 'very_thoughtful',
    surprise_score: 45,
    what_happened: 'Reconnected with friend. Turned out they wanted to reconnect too. Now meeting monthly for coffee.',
    learning_note: 'People often feel the same way but are afraid to reach out first. Vulnerability paid off here.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'as_expected',
    decision_quality: 'very_thoughtful',
    surprise_score: 15,
    what_happened: 'Living comfortably with good financial buffer. Location is farther but not as inconvenient as feared.',
    learning_note: 'Financial security matters more to me than I thought. Prioritizing it was right given my personality.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'slightly_better',
    decision_quality: 'reasonable',
    surprise_score: 35,
    what_happened: 'New PM tool adoption took 2 weeks for team to learn but then productivity jumped 20%. Better than expected.',
    learning_note: 'Upfront investment in learning pays off. Change resistance is normal but benefits were real.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'much_worse',
    decision_quality: 'rushed',
    surprise_score: 80,
    what_happened: 'Project deadline was missed by 2 weeks anyway. Missed vacation AND missed deadline. Worst outcome.',
    learning_note: 'Sacrificing vacation didn\'t help. Poor planning upstream was the real issue. Won\'t skip vacation again.',
    would_repeat: 'no',
  },
  {
    expectation_comparison: 'as_expected',
    decision_quality: 'reasonable',
    surprise_score: 22,
    what_happened: 'Side project started strong but grew to 8 hours/week. Income right but time commitment wasn\'t sustainable.',
    learning_note: 'Projects always expand beyond estimates. Need buffer time in future commitments.',
    would_repeat: 'unsure',
  },
  {
    expectation_comparison: 'slightly_worse',
    decision_quality: 'emotional',
    surprise_score: 75,
    what_happened: 'Cold turkey sugar elimination lasted 3 weeks. Cravings were overwhelming. Went back to old habits.',
    learning_note: 'Extreme approaches don\'t work for me. Gradual reduction would have been smarter. Willpower alone fails.',
    would_repeat: 'no',
  },
  {
    expectation_comparison: 'much_better',
    decision_quality: 'very_thoughtful',
    surprise_score: 20,
    what_happened: 'Course was excellent. Community helped when stuck. Completed in 6 weeks with portfolio project. Worth every cent.',
    learning_note: 'Structured learning with community accountability works for me. Money was an activator for commitment.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'much_better',
    decision_quality: 'very_thoughtful',
    surprise_score: 12,
    what_happened: 'Conversation went better than expected. Coworker didn\'t realize impact. Now we have weekly syncs to prevent it.',
    learning_note: 'Most people respond well to direct, kind feedback. I was more anxious than the situation warranted.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'slightly_better',
    decision_quality: 'very_thoughtful',
    surprise_score: 28,
    what_happened: 'Used car had one transmission issue at 18 months ($2k). Still saved $15k overall. Maintenance costs reasonable.',
    learning_note: 'Risk calculation was right. One expensive repair didn\'t eliminate the value. Good financial call.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'as_expected',
    decision_quality: 'reasonable',
    surprise_score: 32,
    what_happened: 'Meditation became habitual around 5 weeks. Noticing some stress reduction but not as dramatic as hoped.',
    learning_note: 'Benefits are real but gradual. Consistency matters more than intensity. Building 6-month habit now.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'much_better',
    decision_quality: 'very_thoughtful',
    surprise_score: 8,
    what_happened: 'Mediterranean diet feels sustainable. Blood work improved in 8 weeks. Energy levels up consistently.',
    learning_note: 'Long-term health decisions feel different. Patience and sustainability beat quick fixes every time.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'slightly_better',
    decision_quality: 'reasonable',
    surprise_score: 25,
    what_happened: 'Got 12% raise, less than 15% target but more than 0%. Manager acknowledged market reality.',
    learning_note: 'Data and preparation matter. Even 12% is significant long-term. Should negotiate more often.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'much_better',
    decision_quality: 'very_thoughtful',
    surprise_score: 5,
    what_happened: 'Index fund up 8% in 4 months. Low maintenance, sleep well at night. No regrets about missing individual stock plays.',
    learning_note: 'Boring is beautiful in investing. Peace of mind is worth the slightly lower potential returns.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'slightly_better',
    decision_quality: 'reasonable',
    surprise_score: 35,
    what_happened: 'Met interesting people. One connection led to consulting opportunity. More valuable than direct job opportunities.',
    learning_note: 'Networking payoff is indirect and delayed. Glad I stuck with it. Quality over frequency of attendance.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'as_expected',
    decision_quality: 'very_thoughtful',
    surprise_score: 8,
    what_happened: 'Family event was meaningful. Friends understood. Relationships felt more solid afterward.',
    learning_note: 'Aligning decisions with values feels right even when it\'s the harder path. No regrets at all.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'slightly_better',
    decision_quality: 'reasonable',
    surprise_score: 20,
    what_happened: 'New dentist is better. Cleaning was more thorough. Already saving money on recommended work.',
    learning_note: 'Simple research can yield better results. Switching things based on reviews actually works.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'slightly_worse',
    decision_quality: 'reasonable',
    surprise_score: 55,
    what_happened: 'Learning curve steeper than expected. 3 months in and still slow. But fundamentals are solid now.',
    learning_note: 'Initial progress slower than hoped but trajectory is good. Will compound over next 6 months.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'slightly_better',
    decision_quality: 'acceptable',
    surprise_score: 40,
    what_happened: 'Social media time reduced but not as extreme. Now 45 mins daily instead of 2 hours. Sleep quality improved.',
    learning_note: 'Moderation works better than elimination for me. Making progress even if not hitting original target.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'much_better',
    decision_quality: 'very_thoughtful',
    surprise_score: 10,
    what_happened: 'Back pain gone within 2 weeks. Posture improved naturally. Worth every penny. Using it 8 hours daily.',
    learning_note: 'Investing in ergonomics is investing in health. $600 for years of pain-free work is a no-brainer.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'much_better',
    decision_quality: 'reasonable',
    surprise_score: 15,
    what_happened: 'Got interview! Now in second round. Underestimated how companies value potential and attitude over perfect fit.',
    learning_note: 'Risk of rejection is way overblown in my head. Applying to stretch roles is worth it.',
    would_repeat: 'yes',
  },
  {
    expectation_comparison: 'slightly_better',
    decision_quality: 'very_thoughtful',
    surprise_score: 18,
    what_happened: 'Friendship ended cleanly. Initial sadness faded quickly. Replaced with lighter friend group. Stress noticeably lower.',
    learning_note: 'Sometimes protecting your peace is the best investment. No amount of history justifies ongoing toxicity.',
    would_repeat: 'yes',
  },
];

export async function seedDatabase() {
  try {
    // Check if database already has decisions
    const existingCount = await db.decisions.count();
    if (existingCount > 0) {
      console.log(`Database already has ${existingCount} decisions. Skipping seed.`);
      return;
    }

    console.log('Seeding database with sample decisions and reviews...');

    // Add decisions
    const decisionIds = await db.decisions.bulkAdd(sampleDecisions, { allKeys: true });
    console.log(`Added ${decisionIds.length} decisions`);

    // Add reviews with correct decision IDs
    const reviewsWithIds = sampleReviews.map((review, index) => ({
      ...review,
      decision_id: String(decisionIds[index]),
      reviewed_at: new Date(),
      created_at: new Date(),
    }));

    await db.reviews.bulkAdd(reviewsWithIds);
    console.log(`Added ${reviewsWithIds.length} reviews`);

    console.log('Database seeding completed successfully!');
  } catch (error) {
    console.error('Error seeding database:', error);
  }
}
